// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/agent"
	"github.com/plexusone/omniagent/team/ent/agentrole"
	"github.com/plexusone/omniagent/team/ent/predicate"
	"github.com/plexusone/omniagent/team/ent/user"
)

// AgentRoleUpdate is the builder for updating AgentRole entities.
type AgentRoleUpdate struct {
	config
	hooks    []Hook
	mutation *AgentRoleMutation
}

// Where appends a list predicates to the AgentRoleUpdate builder.
func (_u *AgentRoleUpdate) Where(ps ...predicate.AgentRole) *AgentRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentRoleUpdate) SetAgentID(v uuid.UUID) *AgentRoleUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentRoleUpdate) SetNillableAgentID(v *uuid.UUID) *AgentRoleUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentRoleUpdate) SetUserID(v uuid.UUID) *AgentRoleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentRoleUpdate) SetNillableUserID(v *uuid.UUID) *AgentRoleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AgentRoleUpdate) SetRole(v agentrole.Role) *AgentRoleUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AgentRoleUpdate) SetNillableRole(v *agentrole.Role) *AgentRoleUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *AgentRoleUpdate) SetAgent(v *Agent) *AgentRoleUpdate {
	return _u.SetAgentID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AgentRoleUpdate) SetUser(v *User) *AgentRoleUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AgentRoleMutation object of the builder.
func (_u *AgentRoleUpdate) Mutation() *AgentRoleMutation {
	return _u.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *AgentRoleUpdate) ClearAgent() *AgentRoleUpdate {
	_u.mutation.ClearAgent()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AgentRoleUpdate) ClearUser() *AgentRoleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentRoleUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := agentrole.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AgentRole.role": %w`, err)}
		}
	}
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentRole.agent"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentRole.user"`)
	}
	return nil
}

func (_u *AgentRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentrole.Table, agentrole.Columns, sqlgraph.NewFieldSpec(agentrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(agentrole.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.AgentTable,
			Columns: []string{agentrole.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.AgentTable,
			Columns: []string{agentrole.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.UserTable,
			Columns: []string{agentrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.UserTable,
			Columns: []string{agentrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentRoleUpdateOne is the builder for updating a single AgentRole entity.
type AgentRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentRoleMutation
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentRoleUpdateOne) SetAgentID(v uuid.UUID) *AgentRoleUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentRoleUpdateOne) SetNillableAgentID(v *uuid.UUID) *AgentRoleUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentRoleUpdateOne) SetUserID(v uuid.UUID) *AgentRoleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentRoleUpdateOne) SetNillableUserID(v *uuid.UUID) *AgentRoleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AgentRoleUpdateOne) SetRole(v agentrole.Role) *AgentRoleUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AgentRoleUpdateOne) SetNillableRole(v *agentrole.Role) *AgentRoleUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *AgentRoleUpdateOne) SetAgent(v *Agent) *AgentRoleUpdateOne {
	return _u.SetAgentID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AgentRoleUpdateOne) SetUser(v *User) *AgentRoleUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AgentRoleMutation object of the builder.
func (_u *AgentRoleUpdateOne) Mutation() *AgentRoleMutation {
	return _u.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *AgentRoleUpdateOne) ClearAgent() *AgentRoleUpdateOne {
	_u.mutation.ClearAgent()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AgentRoleUpdateOne) ClearUser() *AgentRoleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AgentRoleUpdate builder.
func (_u *AgentRoleUpdateOne) Where(ps ...predicate.AgentRole) *AgentRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentRoleUpdateOne) Select(field string, fields ...string) *AgentRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentRole entity.
func (_u *AgentRoleUpdateOne) Save(ctx context.Context) (*AgentRole, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentRoleUpdateOne) SaveX(ctx context.Context) *AgentRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := agentrole.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AgentRole.role": %w`, err)}
		}
	}
	if _u.mutation.AgentCleared() && len(_u.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentRole.agent"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentRole.user"`)
	}
	return nil
}

func (_u *AgentRoleUpdateOne) sqlSave(ctx context.Context) (_node *AgentRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentrole.Table, agentrole.Columns, sqlgraph.NewFieldSpec(agentrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentrole.FieldID)
		for _, f := range fields {
			if !agentrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(agentrole.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.AgentTable,
			Columns: []string{agentrole.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.AgentTable,
			Columns: []string{agentrole.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.UserTable,
			Columns: []string{agentrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentrole.UserTable,
			Columns: []string{agentrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
