// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniagent/team/ent/agentrole"
	"github.com/plexusone/omniagent/team/ent/predicate"
)

// AgentRoleDelete is the builder for deleting a AgentRole entity.
type AgentRoleDelete struct {
	config
	hooks    []Hook
	mutation *AgentRoleMutation
}

// Where appends a list predicates to the AgentRoleDelete builder.
func (_d *AgentRoleDelete) Where(ps ...predicate.AgentRole) *AgentRoleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentRoleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentRoleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentrole.Table, sqlgraph.NewFieldSpec(agentrole.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentRoleDeleteOne is the builder for deleting a single AgentRole entity.
type AgentRoleDeleteOne struct {
	_d *AgentRoleDelete
}

// Where appends a list predicates to the AgentRoleDelete builder.
func (_d *AgentRoleDeleteOne) Where(ps ...predicate.AgentRole) *AgentRoleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentrole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentRoleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
