// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/agent"
	"github.com/plexusone/omniagent/team/ent/agentskill"
)

// AgentSkill is the model entity for the AgentSkill schema.
type AgentSkill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID uuid.UUID `json:"agent_id,omitempty"`
	// Skill holds the value of the "skill" field.
	Skill string `json:"skill,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentSkillQuery when eager-loading is set.
	Edges        AgentSkillEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentSkillEdges holds the relations/edges for other nodes in the graph.
type AgentSkillEdges struct {
	// Agent holds the value of the agent edge.
	Agent *Agent `json:"agent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AgentOrErr returns the Agent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentSkillEdges) AgentOrErr() (*Agent, error) {
	if e.Agent != nil {
		return e.Agent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "agent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentSkill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentskill.FieldSkill:
			values[i] = new(sql.NullString)
		case agentskill.FieldID, agentskill.FieldAgentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentSkill fields.
func (_m *AgentSkill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentskill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case agentskill.FieldAgentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value != nil {
				_m.AgentID = *value
			}
		case agentskill.FieldSkill:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill", values[i])
			} else if value.Valid {
				_m.Skill = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentSkill.
// This includes values selected through modifiers, order, etc.
func (_m *AgentSkill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAgent queries the "agent" edge of the AgentSkill entity.
func (_m *AgentSkill) QueryAgent() *AgentQuery {
	return NewAgentSkillClient(_m.config).QueryAgent(_m)
}

// Update returns a builder for updating this AgentSkill.
// Note that you need to call AgentSkill.Unwrap() before calling this method if this AgentSkill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentSkill) Update() *AgentSkillUpdateOne {
	return NewAgentSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentSkill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentSkill) Unwrap() *AgentSkill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentSkill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentSkill) String() string {
	var builder strings.Builder
	builder.WriteString("AgentSkill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("agent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentID))
	builder.WriteString(", ")
	builder.WriteString("skill=")
	builder.WriteString(_m.Skill)
	builder.WriteByte(')')
	return builder.String()
}

// AgentSkills is a parsable slice of AgentSkill.
type AgentSkills []*AgentSkill
