// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/agent"
	"github.com/plexusone/omniagent/team/ent/agentrole"
	"github.com/plexusone/omniagent/team/ent/agentskill"
	"github.com/plexusone/omniagent/team/ent/user"
)

// AgentCreate is the builder for creating a Agent entity.
type AgentCreate struct {
	config
	mutation *AgentMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (_c *AgentCreate) SetSlug(v string) *AgentCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AgentCreate) SetName(v string) *AgentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AgentCreate) SetDescription(v string) *AgentCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AgentCreate) SetNillableDescription(v *string) *AgentCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPersona sets the "persona" field.
func (_c *AgentCreate) SetPersona(v string) *AgentCreate {
	_c.mutation.SetPersona(v)
	return _c
}

// SetNillablePersona sets the "persona" field if the given value is not nil.
func (_c *AgentCreate) SetNillablePersona(v *string) *AgentCreate {
	if v != nil {
		_c.SetPersona(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AgentCreate) SetModel(v string) *AgentCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AgentCreate) SetNillableModel(v *string) *AgentCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AgentCreate) SetProvider(v string) *AgentCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AgentCreate) SetNillableProvider(v *string) *AgentCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *AgentCreate) SetVisibility(v agent.Visibility) *AgentCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *AgentCreate) SetNillableVisibility(v *agent.Visibility) *AgentCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetFeatured sets the "featured" field.
func (_c *AgentCreate) SetFeatured(v bool) *AgentCreate {
	_c.mutation.SetFeatured(v)
	return _c
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_c *AgentCreate) SetNillableFeatured(v *bool) *AgentCreate {
	if v != nil {
		_c.SetFeatured(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AgentCreate) SetCreatedBy(v uuid.UUID) *AgentCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCreate) SetCreatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableCreatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentCreate) SetUpdatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableUpdatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentCreate) SetID(v uuid.UUID) *AgentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentCreate) SetNillableID(v *uuid.UUID) *AgentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *AgentCreate) SetCreatorID(id uuid.UUID) *AgentCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *AgentCreate) SetCreator(v *User) *AgentCreate {
	return _c.SetCreatorID(v.ID)
}

// AddSkillIDs adds the "skills" edge to the AgentSkill entity by IDs.
func (_c *AgentCreate) AddSkillIDs(ids ...uuid.UUID) *AgentCreate {
	_c.mutation.AddSkillIDs(ids...)
	return _c
}

// AddSkills adds the "skills" edges to the AgentSkill entity.
func (_c *AgentCreate) AddSkills(v ...*AgentSkill) *AgentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSkillIDs(ids...)
}

// AddRoleIDs adds the "roles" edge to the AgentRole entity by IDs.
func (_c *AgentCreate) AddRoleIDs(ids ...uuid.UUID) *AgentCreate {
	_c.mutation.AddRoleIDs(ids...)
	return _c
}

// AddRoles adds the "roles" edges to the AgentRole entity.
func (_c *AgentCreate) AddRoles(v ...*AgentRole) *AgentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoleIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (_c *AgentCreate) Mutation() *AgentMutation {
	return _c.mutation
}

// Save creates the Agent in the database.
func (_c *AgentCreate) Save(ctx context.Context) (*Agent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCreate) SaveX(ctx context.Context) *Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCreate) defaults() {
	if _, ok := _c.mutation.Visibility(); !ok {
		v := agent.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Featured(); !ok {
		v := agent.DefaultFeatured
		_c.mutation.SetFeatured(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Agent.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := agent.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Agent.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Agent.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "Agent.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := agent.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Agent.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Featured(); !ok {
		return &ValidationError{Name: "featured", err: errors.New(`ent: missing required field "Agent.featured"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Agent.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Agent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Agent.updated_at"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Agent.creator"`)}
	}
	return nil
}

func (_c *AgentCreate) sqlSave(ctx context.Context) (*Agent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCreate) createSpec() (*Agent, *sqlgraph.CreateSpec) {
	var (
		_node = &Agent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agent.Table, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(agent.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Persona(); ok {
		_spec.SetField(agent.FieldPersona, field.TypeString, value)
		_node.Persona = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(agent.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(agent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(agent.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Featured(); ok {
		_spec.SetField(agent.FieldFeatured, field.TypeBool, value)
		_node.Featured = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SkillsTable,
			Columns: []string{agent.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.RolesTable,
			Columns: []string{agent.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentCreateBulk is the builder for creating many Agent entities in bulk.
type AgentCreateBulk struct {
	config
	err      error
	builders []*AgentCreate
}

// Save creates the Agent entities in the database.
func (_c *AgentCreateBulk) Save(ctx context.Context) ([]*Agent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Agent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCreateBulk) SaveX(ctx context.Context) []*Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
