// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/allowlistentry"
	"github.com/plexusone/omniagent/team/ent/predicate"
	"github.com/plexusone/omniagent/team/ent/user"
)

// AllowlistEntryUpdate is the builder for updating AllowlistEntry entities.
type AllowlistEntryUpdate struct {
	config
	hooks    []Hook
	mutation *AllowlistEntryMutation
}

// Where appends a list predicates to the AllowlistEntryUpdate builder.
func (_u *AllowlistEntryUpdate) Where(ps ...predicate.AllowlistEntry) *AllowlistEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *AllowlistEntryUpdate) SetEmail(v string) *AllowlistEntryUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AllowlistEntryUpdate) SetNillableEmail(v *string) *AllowlistEntryUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAddedBy sets the "added_by" field.
func (_u *AllowlistEntryUpdate) SetAddedBy(v uuid.UUID) *AllowlistEntryUpdate {
	_u.mutation.SetAddedBy(v)
	return _u
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_u *AllowlistEntryUpdate) SetNillableAddedBy(v *uuid.UUID) *AllowlistEntryUpdate {
	if v != nil {
		_u.SetAddedBy(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AllowlistEntryUpdate) SetNote(v string) *AllowlistEntryUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AllowlistEntryUpdate) SetNillableNote(v *string) *AllowlistEntryUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AllowlistEntryUpdate) ClearNote() *AllowlistEntryUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetAddedByUserID sets the "added_by_user" edge to the User entity by ID.
func (_u *AllowlistEntryUpdate) SetAddedByUserID(id uuid.UUID) *AllowlistEntryUpdate {
	_u.mutation.SetAddedByUserID(id)
	return _u
}

// SetAddedByUser sets the "added_by_user" edge to the User entity.
func (_u *AllowlistEntryUpdate) SetAddedByUser(v *User) *AllowlistEntryUpdate {
	return _u.SetAddedByUserID(v.ID)
}

// Mutation returns the AllowlistEntryMutation object of the builder.
func (_u *AllowlistEntryUpdate) Mutation() *AllowlistEntryMutation {
	return _u.mutation
}

// ClearAddedByUser clears the "added_by_user" edge to the User entity.
func (_u *AllowlistEntryUpdate) ClearAddedByUser() *AllowlistEntryUpdate {
	_u.mutation.ClearAddedByUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AllowlistEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AllowlistEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AllowlistEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AllowlistEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AllowlistEntryUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := allowlistentry.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AllowlistEntry.email": %w`, err)}
		}
	}
	if _u.mutation.AddedByUserCleared() && len(_u.mutation.AddedByUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AllowlistEntry.added_by_user"`)
	}
	return nil
}

func (_u *AllowlistEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(allowlistentry.Table, allowlistentry.Columns, sqlgraph.NewFieldSpec(allowlistentry.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(allowlistentry.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(allowlistentry.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(allowlistentry.FieldNote, field.TypeString)
	}
	if _u.mutation.AddedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   allowlistentry.AddedByUserTable,
			Columns: []string{allowlistentry.AddedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   allowlistentry.AddedByUserTable,
			Columns: []string{allowlistentry.AddedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{allowlistentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AllowlistEntryUpdateOne is the builder for updating a single AllowlistEntry entity.
type AllowlistEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AllowlistEntryMutation
}

// SetEmail sets the "email" field.
func (_u *AllowlistEntryUpdateOne) SetEmail(v string) *AllowlistEntryUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AllowlistEntryUpdateOne) SetNillableEmail(v *string) *AllowlistEntryUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetAddedBy sets the "added_by" field.
func (_u *AllowlistEntryUpdateOne) SetAddedBy(v uuid.UUID) *AllowlistEntryUpdateOne {
	_u.mutation.SetAddedBy(v)
	return _u
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_u *AllowlistEntryUpdateOne) SetNillableAddedBy(v *uuid.UUID) *AllowlistEntryUpdateOne {
	if v != nil {
		_u.SetAddedBy(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AllowlistEntryUpdateOne) SetNote(v string) *AllowlistEntryUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AllowlistEntryUpdateOne) SetNillableNote(v *string) *AllowlistEntryUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AllowlistEntryUpdateOne) ClearNote() *AllowlistEntryUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetAddedByUserID sets the "added_by_user" edge to the User entity by ID.
func (_u *AllowlistEntryUpdateOne) SetAddedByUserID(id uuid.UUID) *AllowlistEntryUpdateOne {
	_u.mutation.SetAddedByUserID(id)
	return _u
}

// SetAddedByUser sets the "added_by_user" edge to the User entity.
func (_u *AllowlistEntryUpdateOne) SetAddedByUser(v *User) *AllowlistEntryUpdateOne {
	return _u.SetAddedByUserID(v.ID)
}

// Mutation returns the AllowlistEntryMutation object of the builder.
func (_u *AllowlistEntryUpdateOne) Mutation() *AllowlistEntryMutation {
	return _u.mutation
}

// ClearAddedByUser clears the "added_by_user" edge to the User entity.
func (_u *AllowlistEntryUpdateOne) ClearAddedByUser() *AllowlistEntryUpdateOne {
	_u.mutation.ClearAddedByUser()
	return _u
}

// Where appends a list predicates to the AllowlistEntryUpdate builder.
func (_u *AllowlistEntryUpdateOne) Where(ps ...predicate.AllowlistEntry) *AllowlistEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AllowlistEntryUpdateOne) Select(field string, fields ...string) *AllowlistEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AllowlistEntry entity.
func (_u *AllowlistEntryUpdateOne) Save(ctx context.Context) (*AllowlistEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AllowlistEntryUpdateOne) SaveX(ctx context.Context) *AllowlistEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AllowlistEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AllowlistEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AllowlistEntryUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := allowlistentry.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AllowlistEntry.email": %w`, err)}
		}
	}
	if _u.mutation.AddedByUserCleared() && len(_u.mutation.AddedByUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AllowlistEntry.added_by_user"`)
	}
	return nil
}

func (_u *AllowlistEntryUpdateOne) sqlSave(ctx context.Context) (_node *AllowlistEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(allowlistentry.Table, allowlistentry.Columns, sqlgraph.NewFieldSpec(allowlistentry.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AllowlistEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, allowlistentry.FieldID)
		for _, f := range fields {
			if !allowlistentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != allowlistentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(allowlistentry.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(allowlistentry.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(allowlistentry.FieldNote, field.TypeString)
	}
	if _u.mutation.AddedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   allowlistentry.AddedByUserTable,
			Columns: []string{allowlistentry.AddedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   allowlistentry.AddedByUserTable,
			Columns: []string{allowlistentry.AddedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AllowlistEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{allowlistentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
