// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/allowlistentry"
	"github.com/plexusone/omniagent/team/ent/user"
)

// AllowlistEntryCreate is the builder for creating a AllowlistEntry entity.
type AllowlistEntryCreate struct {
	config
	mutation *AllowlistEntryMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *AllowlistEntryCreate) SetEmail(v string) *AllowlistEntryCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetAddedBy sets the "added_by" field.
func (_c *AllowlistEntryCreate) SetAddedBy(v uuid.UUID) *AllowlistEntryCreate {
	_c.mutation.SetAddedBy(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *AllowlistEntryCreate) SetNote(v string) *AllowlistEntryCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *AllowlistEntryCreate) SetNillableNote(v *string) *AllowlistEntryCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AllowlistEntryCreate) SetCreatedAt(v time.Time) *AllowlistEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AllowlistEntryCreate) SetNillableCreatedAt(v *time.Time) *AllowlistEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AllowlistEntryCreate) SetID(v uuid.UUID) *AllowlistEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AllowlistEntryCreate) SetNillableID(v *uuid.UUID) *AllowlistEntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAddedByUserID sets the "added_by_user" edge to the User entity by ID.
func (_c *AllowlistEntryCreate) SetAddedByUserID(id uuid.UUID) *AllowlistEntryCreate {
	_c.mutation.SetAddedByUserID(id)
	return _c
}

// SetAddedByUser sets the "added_by_user" edge to the User entity.
func (_c *AllowlistEntryCreate) SetAddedByUser(v *User) *AllowlistEntryCreate {
	return _c.SetAddedByUserID(v.ID)
}

// Mutation returns the AllowlistEntryMutation object of the builder.
func (_c *AllowlistEntryCreate) Mutation() *AllowlistEntryMutation {
	return _c.mutation
}

// Save creates the AllowlistEntry in the database.
func (_c *AllowlistEntryCreate) Save(ctx context.Context) (*AllowlistEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AllowlistEntryCreate) SaveX(ctx context.Context) *AllowlistEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AllowlistEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AllowlistEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AllowlistEntryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := allowlistentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := allowlistentry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AllowlistEntryCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AllowlistEntry.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := allowlistentry.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AllowlistEntry.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddedBy(); !ok {
		return &ValidationError{Name: "added_by", err: errors.New(`ent: missing required field "AllowlistEntry.added_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AllowlistEntry.created_at"`)}
	}
	if len(_c.mutation.AddedByUserIDs()) == 0 {
		return &ValidationError{Name: "added_by_user", err: errors.New(`ent: missing required edge "AllowlistEntry.added_by_user"`)}
	}
	return nil
}

func (_c *AllowlistEntryCreate) sqlSave(ctx context.Context) (*AllowlistEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AllowlistEntryCreate) createSpec() (*AllowlistEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &AllowlistEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(allowlistentry.Table, sqlgraph.NewFieldSpec(allowlistentry.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(allowlistentry.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(allowlistentry.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(allowlistentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AddedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   allowlistentry.AddedByUserTable,
			Columns: []string{allowlistentry.AddedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AddedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AllowlistEntryCreateBulk is the builder for creating many AllowlistEntry entities in bulk.
type AllowlistEntryCreateBulk struct {
	config
	err      error
	builders []*AllowlistEntryCreate
}

// Save creates the AllowlistEntry entities in the database.
func (_c *AllowlistEntryCreateBulk) Save(ctx context.Context) ([]*AllowlistEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AllowlistEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AllowlistEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AllowlistEntryCreateBulk) SaveX(ctx context.Context) []*AllowlistEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AllowlistEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AllowlistEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
