// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/authsession"
	"github.com/plexusone/omniagent/team/ent/predicate"
	"github.com/plexusone/omniagent/team/ent/user"
)

// AuthSessionUpdate is the builder for updating AuthSession entities.
type AuthSessionUpdate struct {
	config
	hooks    []Hook
	mutation *AuthSessionMutation
}

// Where appends a list predicates to the AuthSessionUpdate builder.
func (_u *AuthSessionUpdate) Where(ps ...predicate.AuthSession) *AuthSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthSessionUpdate) SetUserID(v uuid.UUID) *AuthSessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableUserID(v *uuid.UUID) *AuthSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AuthSessionUpdate) SetTokenHash(v string) *AuthSessionUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableTokenHash(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AuthSessionUpdate) SetLastSeenAt(v time.Time) *AuthSessionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableLastSeenAt(v *time.Time) *AuthSessionUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthSessionUpdate) SetExpiresAt(v time.Time) *AuthSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableExpiresAt(v *time.Time) *AuthSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuthSessionUpdate) SetUserAgent(v string) *AuthSessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableUserAgent(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuthSessionUpdate) ClearUserAgent() *AuthSessionUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetCreatedIP sets the "created_ip" field.
func (_u *AuthSessionUpdate) SetCreatedIP(v string) *AuthSessionUpdate {
	_u.mutation.SetCreatedIP(v)
	return _u
}

// SetNillableCreatedIP sets the "created_ip" field if the given value is not nil.
func (_u *AuthSessionUpdate) SetNillableCreatedIP(v *string) *AuthSessionUpdate {
	if v != nil {
		_u.SetCreatedIP(*v)
	}
	return _u
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (_u *AuthSessionUpdate) ClearCreatedIP() *AuthSessionUpdate {
	_u.mutation.ClearCreatedIP()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AuthSessionUpdate) SetUser(v *User) *AuthSessionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_u *AuthSessionUpdate) Mutation() *AuthSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthSessionUpdate) ClearUser() *AuthSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthSessionUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := authsession.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "AuthSession.token_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthSession.user"`)
	}
	return nil
}

func (_u *AuthSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authsession.Table, authsession.Columns, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(authsession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(authsession.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(authsession.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(authsession.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedIP(); ok {
		_spec.SetField(authsession.FieldCreatedIP, field.TypeString, value)
	}
	if _u.mutation.CreatedIPCleared() {
		_spec.ClearField(authsession.FieldCreatedIP, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authsession.UserTable,
			Columns: []string{authsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authsession.UserTable,
			Columns: []string{authsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthSessionUpdateOne is the builder for updating a single AuthSession entity.
type AuthSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthSessionMutation
}

// SetUserID sets the "user_id" field.
func (_u *AuthSessionUpdateOne) SetUserID(v uuid.UUID) *AuthSessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableUserID(v *uuid.UUID) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AuthSessionUpdateOne) SetTokenHash(v string) *AuthSessionUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableTokenHash(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AuthSessionUpdateOne) SetLastSeenAt(v time.Time) *AuthSessionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableLastSeenAt(v *time.Time) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthSessionUpdateOne) SetExpiresAt(v time.Time) *AuthSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AuthSessionUpdateOne) SetUserAgent(v string) *AuthSessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableUserAgent(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AuthSessionUpdateOne) ClearUserAgent() *AuthSessionUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetCreatedIP sets the "created_ip" field.
func (_u *AuthSessionUpdateOne) SetCreatedIP(v string) *AuthSessionUpdateOne {
	_u.mutation.SetCreatedIP(v)
	return _u
}

// SetNillableCreatedIP sets the "created_ip" field if the given value is not nil.
func (_u *AuthSessionUpdateOne) SetNillableCreatedIP(v *string) *AuthSessionUpdateOne {
	if v != nil {
		_u.SetCreatedIP(*v)
	}
	return _u
}

// ClearCreatedIP clears the value of the "created_ip" field.
func (_u *AuthSessionUpdateOne) ClearCreatedIP() *AuthSessionUpdateOne {
	_u.mutation.ClearCreatedIP()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AuthSessionUpdateOne) SetUser(v *User) *AuthSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_u *AuthSessionUpdateOne) Mutation() *AuthSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthSessionUpdateOne) ClearUser() *AuthSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AuthSessionUpdate builder.
func (_u *AuthSessionUpdateOne) Where(ps ...predicate.AuthSession) *AuthSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthSessionUpdateOne) Select(field string, fields ...string) *AuthSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthSession entity.
func (_u *AuthSessionUpdateOne) Save(ctx context.Context) (*AuthSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthSessionUpdateOne) SaveX(ctx context.Context) *AuthSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthSessionUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := authsession.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "AuthSession.token_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthSession.user"`)
	}
	return nil
}

func (_u *AuthSessionUpdateOne) sqlSave(ctx context.Context) (_node *AuthSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authsession.Table, authsession.Columns, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authsession.FieldID)
		for _, f := range fields {
			if !authsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(authsession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(authsession.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(authsession.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(authsession.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedIP(); ok {
		_spec.SetField(authsession.FieldCreatedIP, field.TypeString, value)
	}
	if _u.mutation.CreatedIPCleared() {
		_spec.ClearField(authsession.FieldCreatedIP, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authsession.UserTable,
			Columns: []string{authsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authsession.UserTable,
			Columns: []string{authsession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuthSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
