// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/chat"
	"github.com/plexusone/omniagent/team/ent/chatmember"
	"github.com/plexusone/omniagent/team/ent/user"
)

// ChatMember is the model entity for the ChatMember schema.
type ChatMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ChatID holds the value of the "chat_id" field.
	ChatID uuid.UUID `json:"chat_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role chatmember.Role `json:"role,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatMemberQuery when eager-loading is set.
	Edges        ChatMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatMemberEdges holds the relations/edges for other nodes in the graph.
type ChatMemberEdges struct {
	// Chat holds the value of the chat edge.
	Chat *Chat `json:"chat,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChatOrErr returns the Chat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMemberEdges) ChatOrErr() (*Chat, error) {
	if e.Chat != nil {
		return e.Chat, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chat.Label}
	}
	return nil, &NotLoadedError{edge: "chat"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatmember.FieldRole:
			values[i] = new(sql.NullString)
		case chatmember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case chatmember.FieldID, chatmember.FieldChatID, chatmember.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatMember fields.
func (_m *ChatMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatmember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case chatmember.FieldChatID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field chat_id", values[i])
			} else if value != nil {
				_m.ChatID = *value
			}
		case chatmember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case chatmember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = chatmember.Role(value.String)
			}
		case chatmember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatMember.
// This includes values selected through modifiers, order, etc.
func (_m *ChatMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChat queries the "chat" edge of the ChatMember entity.
func (_m *ChatMember) QueryChat() *ChatQuery {
	return NewChatMemberClient(_m.config).QueryChat(_m)
}

// QueryUser queries the "user" edge of the ChatMember entity.
func (_m *ChatMember) QueryUser() *UserQuery {
	return NewChatMemberClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ChatMember.
// Note that you need to call ChatMember.Unwrap() before calling this method if this ChatMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatMember) Update() *ChatMemberUpdateOne {
	return NewChatMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatMember) Unwrap() *ChatMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatMember) String() string {
	var builder strings.Builder
	builder.WriteString("ChatMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chat_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChatID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatMembers is a parsable slice of ChatMember.
type ChatMembers []*ChatMember
