// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/chat"
	"github.com/plexusone/omniagent/team/ent/chatmember"
	"github.com/plexusone/omniagent/team/ent/user"
)

// ChatMemberCreate is the builder for creating a ChatMember entity.
type ChatMemberCreate struct {
	config
	mutation *ChatMemberMutation
	hooks    []Hook
}

// SetChatID sets the "chat_id" field.
func (_c *ChatMemberCreate) SetChatID(v uuid.UUID) *ChatMemberCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatMemberCreate) SetUserID(v uuid.UUID) *ChatMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ChatMemberCreate) SetRole(v chatmember.Role) *ChatMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *ChatMemberCreate) SetNillableRole(v *chatmember.Role) *ChatMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *ChatMemberCreate) SetJoinedAt(v time.Time) *ChatMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *ChatMemberCreate) SetNillableJoinedAt(v *time.Time) *ChatMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChatMemberCreate) SetID(v uuid.UUID) *ChatMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChatMemberCreate) SetNillableID(v *uuid.UUID) *ChatMemberCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChat sets the "chat" edge to the Chat entity.
func (_c *ChatMemberCreate) SetChat(v *Chat) *ChatMemberCreate {
	return _c.SetChatID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatMemberCreate) SetUser(v *User) *ChatMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ChatMemberMutation object of the builder.
func (_c *ChatMemberCreate) Mutation() *ChatMemberMutation {
	return _c.mutation
}

// Save creates the ChatMember in the database.
func (_c *ChatMemberCreate) Save(ctx context.Context) (*ChatMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatMemberCreate) SaveX(ctx context.Context) *ChatMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatMemberCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := chatmember.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := chatmember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chatmember.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatMemberCreate) check() error {
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "ChatMember.chat_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatMember.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ChatMember.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := chatmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatMember.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "ChatMember.joined_at"`)}
	}
	if len(_c.mutation.ChatIDs()) == 0 {
		return &ValidationError{Name: "chat", err: errors.New(`ent: missing required edge "ChatMember.chat"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChatMember.user"`)}
	}
	return nil
}

func (_c *ChatMemberCreate) sqlSave(ctx context.Context) (*ChatMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatMemberCreate) createSpec() (*ChatMember, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatmember.Table, sqlgraph.NewFieldSpec(chatmember.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(chatmember.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(chatmember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := _c.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.ChatTable,
			Columns: []string{chatmember.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChatID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmember.UserTable,
			Columns: []string{chatmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatMemberCreateBulk is the builder for creating many ChatMember entities in bulk.
type ChatMemberCreateBulk struct {
	config
	err      error
	builders []*ChatMemberCreate
}

// Save creates the ChatMember entities in the database.
func (_c *ChatMemberCreateBulk) Save(ctx context.Context) ([]*ChatMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatMemberCreateBulk) SaveX(ctx context.Context) []*ChatMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
