// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/magiclinktoken"
)

// MagicLinkTokenCreate is the builder for creating a MagicLinkToken entity.
type MagicLinkTokenCreate struct {
	config
	mutation *MagicLinkTokenMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *MagicLinkTokenCreate) SetEmail(v string) *MagicLinkTokenCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *MagicLinkTokenCreate) SetTokenHash(v string) *MagicLinkTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *MagicLinkTokenCreate) SetExpiresAt(v time.Time) *MagicLinkTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *MagicLinkTokenCreate) SetConsumedAt(v time.Time) *MagicLinkTokenCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *MagicLinkTokenCreate) SetNillableConsumedAt(v *time.Time) *MagicLinkTokenCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetCreatedIP sets the "created_ip" field.
func (_c *MagicLinkTokenCreate) SetCreatedIP(v string) *MagicLinkTokenCreate {
	_c.mutation.SetCreatedIP(v)
	return _c
}

// SetNillableCreatedIP sets the "created_ip" field if the given value is not nil.
func (_c *MagicLinkTokenCreate) SetNillableCreatedIP(v *string) *MagicLinkTokenCreate {
	if v != nil {
		_c.SetCreatedIP(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MagicLinkTokenCreate) SetCreatedAt(v time.Time) *MagicLinkTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MagicLinkTokenCreate) SetNillableCreatedAt(v *time.Time) *MagicLinkTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MagicLinkTokenCreate) SetID(v uuid.UUID) *MagicLinkTokenCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MagicLinkTokenCreate) SetNillableID(v *uuid.UUID) *MagicLinkTokenCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MagicLinkTokenMutation object of the builder.
func (_c *MagicLinkTokenCreate) Mutation() *MagicLinkTokenMutation {
	return _c.mutation
}

// Save creates the MagicLinkToken in the database.
func (_c *MagicLinkTokenCreate) Save(ctx context.Context) (*MagicLinkToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MagicLinkTokenCreate) SaveX(ctx context.Context) *MagicLinkToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MagicLinkTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MagicLinkTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MagicLinkTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := magiclinktoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := magiclinktoken.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MagicLinkTokenCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "MagicLinkToken.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := magiclinktoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "MagicLinkToken.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "MagicLinkToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := magiclinktoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "MagicLinkToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "MagicLinkToken.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MagicLinkToken.created_at"`)}
	}
	return nil
}

func (_c *MagicLinkTokenCreate) sqlSave(ctx context.Context) (*MagicLinkToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MagicLinkTokenCreate) createSpec() (*MagicLinkToken, *sqlgraph.CreateSpec) {
	var (
		_node = &MagicLinkToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(magiclinktoken.Table, sqlgraph.NewFieldSpec(magiclinktoken.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(magiclinktoken.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(magiclinktoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(magiclinktoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(magiclinktoken.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.CreatedIP(); ok {
		_spec.SetField(magiclinktoken.FieldCreatedIP, field.TypeString, value)
		_node.CreatedIP = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(magiclinktoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MagicLinkTokenCreateBulk is the builder for creating many MagicLinkToken entities in bulk.
type MagicLinkTokenCreateBulk struct {
	config
	err      error
	builders []*MagicLinkTokenCreate
}

// Save creates the MagicLinkToken entities in the database.
func (_c *MagicLinkTokenCreateBulk) Save(ctx context.Context) ([]*MagicLinkToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MagicLinkToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MagicLinkTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MagicLinkTokenCreateBulk) SaveX(ctx context.Context) []*MagicLinkToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MagicLinkTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MagicLinkTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
