// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/chat"
	"github.com/plexusone/omniagent/team/ent/message"
	"github.com/plexusone/omniagent/team/ent/predicate"
	"github.com/plexusone/omniagent/team/ent/user"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *MessageUpdate) SetChatID(v uuid.UUID) *MessageUpdate {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableChatID(v *uuid.UUID) *MessageUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetAuthorType sets the "author_type" field.
func (_u *MessageUpdate) SetAuthorType(v message.AuthorType) *MessageUpdate {
	_u.mutation.SetAuthorType(v)
	return _u
}

// SetNillableAuthorType sets the "author_type" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableAuthorType(v *message.AuthorType) *MessageUpdate {
	if v != nil {
		_u.SetAuthorType(*v)
	}
	return _u
}

// SetAuthorUserID sets the "author_user_id" field.
func (_u *MessageUpdate) SetAuthorUserID(v uuid.UUID) *MessageUpdate {
	_u.mutation.SetAuthorUserID(v)
	return _u
}

// SetNillableAuthorUserID sets the "author_user_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableAuthorUserID(v *uuid.UUID) *MessageUpdate {
	if v != nil {
		_u.SetAuthorUserID(*v)
	}
	return _u
}

// ClearAuthorUserID clears the value of the "author_user_id" field.
func (_u *MessageUpdate) ClearAuthorUserID() *MessageUpdate {
	_u.mutation.ClearAuthorUserID()
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *MessageUpdate) SetChat(v *Chat) *MessageUpdate {
	return _u.SetChatID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *MessageUpdate) SetAuthorID(id uuid.UUID) *MessageUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (_u *MessageUpdate) SetNillableAuthorID(id *uuid.UUID) *MessageUpdate {
	if id != nil {
		_u = _u.SetAuthorID(*id)
	}
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *MessageUpdate) SetAuthor(v *User) *MessageUpdate {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *MessageUpdate) ClearChat() *MessageUpdate {
	_u.mutation.ClearChat()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *MessageUpdate) ClearAuthor() *MessageUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.AuthorType(); ok {
		if err := message.AuthorTypeValidator(v); err != nil {
			return &ValidationError{Name: "author_type", err: fmt.Errorf(`ent: validator failed for field "Message.author_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := message.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Message.content": %w`, err)}
		}
	}
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.chat"`)
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorType(); ok {
		_spec.SetField(message.FieldAuthorType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetChatID sets the "chat_id" field.
func (_u *MessageUpdateOne) SetChatID(v uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableChatID(v *uuid.UUID) *MessageUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetAuthorType sets the "author_type" field.
func (_u *MessageUpdateOne) SetAuthorType(v message.AuthorType) *MessageUpdateOne {
	_u.mutation.SetAuthorType(v)
	return _u
}

// SetNillableAuthorType sets the "author_type" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableAuthorType(v *message.AuthorType) *MessageUpdateOne {
	if v != nil {
		_u.SetAuthorType(*v)
	}
	return _u
}

// SetAuthorUserID sets the "author_user_id" field.
func (_u *MessageUpdateOne) SetAuthorUserID(v uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetAuthorUserID(v)
	return _u
}

// SetNillableAuthorUserID sets the "author_user_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableAuthorUserID(v *uuid.UUID) *MessageUpdateOne {
	if v != nil {
		_u.SetAuthorUserID(*v)
	}
	return _u
}

// ClearAuthorUserID clears the value of the "author_user_id" field.
func (_u *MessageUpdateOne) ClearAuthorUserID() *MessageUpdateOne {
	_u.mutation.ClearAuthorUserID()
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetChat sets the "chat" edge to the Chat entity.
func (_u *MessageUpdateOne) SetChat(v *Chat) *MessageUpdateOne {
	return _u.SetChatID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *MessageUpdateOne) SetAuthorID(id uuid.UUID) *MessageUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableAuthorID(id *uuid.UUID) *MessageUpdateOne {
	if id != nil {
		_u = _u.SetAuthorID(*id)
	}
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *MessageUpdateOne) SetAuthor(v *User) *MessageUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (_u *MessageUpdateOne) ClearChat() *MessageUpdateOne {
	_u.mutation.ClearChat()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *MessageUpdateOne) ClearAuthor() *MessageUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.AuthorType(); ok {
		if err := message.AuthorTypeValidator(v); err != nil {
			return &ValidationError{Name: "author_type", err: fmt.Errorf(`ent: validator failed for field "Message.author_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := message.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Message.content": %w`, err)}
		}
	}
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.chat"`)
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorType(); ok {
		_spec.SetField(message.FieldAuthorType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.AuthorTable,
			Columns: []string{message.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
