// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/agent"
	"github.com/plexusone/omniagent/team/ent/agentrole"
	"github.com/plexusone/omniagent/team/ent/agentskill"
	"github.com/plexusone/omniagent/team/ent/allowlistentry"
	"github.com/plexusone/omniagent/team/ent/authsession"
	"github.com/plexusone/omniagent/team/ent/chat"
	"github.com/plexusone/omniagent/team/ent/chatmember"
	"github.com/plexusone/omniagent/team/ent/identity"
	"github.com/plexusone/omniagent/team/ent/magiclinktoken"
	"github.com/plexusone/omniagent/team/ent/message"
	"github.com/plexusone/omniagent/team/ent/schema"
	"github.com/plexusone/omniagent/team/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescSlug is the schema descriptor for slug field.
	agentDescSlug := agentFields[1].Descriptor()
	// agent.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	agent.SlugValidator = agentDescSlug.Validators[0].(func(string) error)
	// agentDescName is the schema descriptor for name field.
	agentDescName := agentFields[2].Descriptor()
	// agent.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agent.NameValidator = agentDescName.Validators[0].(func(string) error)
	// agentDescFeatured is the schema descriptor for featured field.
	agentDescFeatured := agentFields[8].Descriptor()
	// agent.DefaultFeatured holds the default value on creation for the featured field.
	agent.DefaultFeatured = agentDescFeatured.Default.(bool)
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentFields[10].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescUpdatedAt is the schema descriptor for updated_at field.
	agentDescUpdatedAt := agentFields[11].Descriptor()
	// agent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agent.DefaultUpdatedAt = agentDescUpdatedAt.Default.(func() time.Time)
	// agent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agent.UpdateDefaultUpdatedAt = agentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	agentroleFields := schema.AgentRole{}.Fields()
	_ = agentroleFields
	// agentroleDescCreatedAt is the schema descriptor for created_at field.
	agentroleDescCreatedAt := agentroleFields[4].Descriptor()
	// agentrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentrole.DefaultCreatedAt = agentroleDescCreatedAt.Default.(func() time.Time)
	// agentroleDescID is the schema descriptor for id field.
	agentroleDescID := agentroleFields[0].Descriptor()
	// agentrole.DefaultID holds the default value on creation for the id field.
	agentrole.DefaultID = agentroleDescID.Default.(func() uuid.UUID)
	agentskillFields := schema.AgentSkill{}.Fields()
	_ = agentskillFields
	// agentskillDescSkill is the schema descriptor for skill field.
	agentskillDescSkill := agentskillFields[2].Descriptor()
	// agentskill.SkillValidator is a validator for the "skill" field. It is called by the builders before save.
	agentskill.SkillValidator = agentskillDescSkill.Validators[0].(func(string) error)
	// agentskillDescID is the schema descriptor for id field.
	agentskillDescID := agentskillFields[0].Descriptor()
	// agentskill.DefaultID holds the default value on creation for the id field.
	agentskill.DefaultID = agentskillDescID.Default.(func() uuid.UUID)
	allowlistentryFields := schema.AllowlistEntry{}.Fields()
	_ = allowlistentryFields
	// allowlistentryDescEmail is the schema descriptor for email field.
	allowlistentryDescEmail := allowlistentryFields[1].Descriptor()
	// allowlistentry.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	allowlistentry.EmailValidator = allowlistentryDescEmail.Validators[0].(func(string) error)
	// allowlistentryDescCreatedAt is the schema descriptor for created_at field.
	allowlistentryDescCreatedAt := allowlistentryFields[4].Descriptor()
	// allowlistentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	allowlistentry.DefaultCreatedAt = allowlistentryDescCreatedAt.Default.(func() time.Time)
	// allowlistentryDescID is the schema descriptor for id field.
	allowlistentryDescID := allowlistentryFields[0].Descriptor()
	// allowlistentry.DefaultID holds the default value on creation for the id field.
	allowlistentry.DefaultID = allowlistentryDescID.Default.(func() uuid.UUID)
	authsessionFields := schema.AuthSession{}.Fields()
	_ = authsessionFields
	// authsessionDescTokenHash is the schema descriptor for token_hash field.
	authsessionDescTokenHash := authsessionFields[2].Descriptor()
	// authsession.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	authsession.TokenHashValidator = authsessionDescTokenHash.Validators[0].(func(string) error)
	// authsessionDescCreatedAt is the schema descriptor for created_at field.
	authsessionDescCreatedAt := authsessionFields[3].Descriptor()
	// authsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	authsession.DefaultCreatedAt = authsessionDescCreatedAt.Default.(func() time.Time)
	// authsessionDescLastSeenAt is the schema descriptor for last_seen_at field.
	authsessionDescLastSeenAt := authsessionFields[4].Descriptor()
	// authsession.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	authsession.DefaultLastSeenAt = authsessionDescLastSeenAt.Default.(func() time.Time)
	// authsessionDescID is the schema descriptor for id field.
	authsessionDescID := authsessionFields[0].Descriptor()
	// authsession.DefaultID holds the default value on creation for the id field.
	authsession.DefaultID = authsessionDescID.Default.(func() uuid.UUID)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescCreatedAt is the schema descriptor for created_at field.
	chatDescCreatedAt := chatFields[5].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the created_at field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	// chatDescID is the schema descriptor for id field.
	chatDescID := chatFields[0].Descriptor()
	// chat.DefaultID holds the default value on creation for the id field.
	chat.DefaultID = chatDescID.Default.(func() uuid.UUID)
	chatmemberFields := schema.ChatMember{}.Fields()
	_ = chatmemberFields
	// chatmemberDescJoinedAt is the schema descriptor for joined_at field.
	chatmemberDescJoinedAt := chatmemberFields[4].Descriptor()
	// chatmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	chatmember.DefaultJoinedAt = chatmemberDescJoinedAt.Default.(func() time.Time)
	// chatmemberDescID is the schema descriptor for id field.
	chatmemberDescID := chatmemberFields[0].Descriptor()
	// chatmember.DefaultID holds the default value on creation for the id field.
	chatmember.DefaultID = chatmemberDescID.Default.(func() uuid.UUID)
	identityFields := schema.Identity{}.Fields()
	_ = identityFields
	// identityDescProviderSubject is the schema descriptor for provider_subject field.
	identityDescProviderSubject := identityFields[3].Descriptor()
	// identity.ProviderSubjectValidator is a validator for the "provider_subject" field. It is called by the builders before save.
	identity.ProviderSubjectValidator = identityDescProviderSubject.Validators[0].(func(string) error)
	// identityDescVerifiedEmail is the schema descriptor for verified_email field.
	identityDescVerifiedEmail := identityFields[4].Descriptor()
	// identity.VerifiedEmailValidator is a validator for the "verified_email" field. It is called by the builders before save.
	identity.VerifiedEmailValidator = identityDescVerifiedEmail.Validators[0].(func(string) error)
	// identityDescCreatedAt is the schema descriptor for created_at field.
	identityDescCreatedAt := identityFields[5].Descriptor()
	// identity.DefaultCreatedAt holds the default value on creation for the created_at field.
	identity.DefaultCreatedAt = identityDescCreatedAt.Default.(func() time.Time)
	// identityDescID is the schema descriptor for id field.
	identityDescID := identityFields[0].Descriptor()
	// identity.DefaultID holds the default value on creation for the id field.
	identity.DefaultID = identityDescID.Default.(func() uuid.UUID)
	magiclinktokenFields := schema.MagicLinkToken{}.Fields()
	_ = magiclinktokenFields
	// magiclinktokenDescEmail is the schema descriptor for email field.
	magiclinktokenDescEmail := magiclinktokenFields[1].Descriptor()
	// magiclinktoken.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	magiclinktoken.EmailValidator = magiclinktokenDescEmail.Validators[0].(func(string) error)
	// magiclinktokenDescTokenHash is the schema descriptor for token_hash field.
	magiclinktokenDescTokenHash := magiclinktokenFields[2].Descriptor()
	// magiclinktoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	magiclinktoken.TokenHashValidator = magiclinktokenDescTokenHash.Validators[0].(func(string) error)
	// magiclinktokenDescCreatedAt is the schema descriptor for created_at field.
	magiclinktokenDescCreatedAt := magiclinktokenFields[6].Descriptor()
	// magiclinktoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	magiclinktoken.DefaultCreatedAt = magiclinktokenDescCreatedAt.Default.(func() time.Time)
	// magiclinktokenDescID is the schema descriptor for id field.
	magiclinktokenDescID := magiclinktokenFields[0].Descriptor()
	// magiclinktoken.DefaultID holds the default value on creation for the id field.
	magiclinktoken.DefaultID = magiclinktokenDescID.Default.(func() uuid.UUID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[4].Descriptor()
	// message.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	message.ContentValidator = messageDescContent.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[5].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
