// Code generated by ent, DO NOT EDIT.

package magiclinktoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexusone/omniagent/team/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldEmail, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedIP applies equality check predicate on the "created_ip" field. It's identical to CreatedIPEQ.
func CreatedIP(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldCreatedIP, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldCreatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldContainsFold(FieldEmail, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotNull(FieldConsumedAt))
}

// CreatedIPEQ applies the EQ predicate on the "created_ip" field.
func CreatedIPEQ(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldCreatedIP, v))
}

// CreatedIPNEQ applies the NEQ predicate on the "created_ip" field.
func CreatedIPNEQ(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNEQ(FieldCreatedIP, v))
}

// CreatedIPIn applies the In predicate on the "created_ip" field.
func CreatedIPIn(vs ...string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIn(FieldCreatedIP, vs...))
}

// CreatedIPNotIn applies the NotIn predicate on the "created_ip" field.
func CreatedIPNotIn(vs ...string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotIn(FieldCreatedIP, vs...))
}

// CreatedIPGT applies the GT predicate on the "created_ip" field.
func CreatedIPGT(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGT(FieldCreatedIP, v))
}

// CreatedIPGTE applies the GTE predicate on the "created_ip" field.
func CreatedIPGTE(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGTE(FieldCreatedIP, v))
}

// CreatedIPLT applies the LT predicate on the "created_ip" field.
func CreatedIPLT(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLT(FieldCreatedIP, v))
}

// CreatedIPLTE applies the LTE predicate on the "created_ip" field.
func CreatedIPLTE(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLTE(FieldCreatedIP, v))
}

// CreatedIPContains applies the Contains predicate on the "created_ip" field.
func CreatedIPContains(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldContains(FieldCreatedIP, v))
}

// CreatedIPHasPrefix applies the HasPrefix predicate on the "created_ip" field.
func CreatedIPHasPrefix(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldHasPrefix(FieldCreatedIP, v))
}

// CreatedIPHasSuffix applies the HasSuffix predicate on the "created_ip" field.
func CreatedIPHasSuffix(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldHasSuffix(FieldCreatedIP, v))
}

// CreatedIPIsNil applies the IsNil predicate on the "created_ip" field.
func CreatedIPIsNil() predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIsNull(FieldCreatedIP))
}

// CreatedIPNotNil applies the NotNil predicate on the "created_ip" field.
func CreatedIPNotNil() predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotNull(FieldCreatedIP))
}

// CreatedIPEqualFold applies the EqualFold predicate on the "created_ip" field.
func CreatedIPEqualFold(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEqualFold(FieldCreatedIP, v))
}

// CreatedIPContainsFold applies the ContainsFold predicate on the "created_ip" field.
func CreatedIPContainsFold(v string) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldContainsFold(FieldCreatedIP, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MagicLinkToken) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MagicLinkToken) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MagicLinkToken) predicate.MagicLinkToken {
	return predicate.MagicLinkToken(sql.NotPredicates(p))
}
